project:
  type: book
  output-dir: docs

toc: true
number-sections: true


book:
  title: "A Quick Introduction to R For Researchers"
  date: "6/16/2022"
  chapters:
    - index.qmd
    - 1_installation.qmd
    - 2_navigating.qmd
    - 3_wrangling.qmd

format:
  html:
    theme: cosmo
    number-depth: 2
    suppress-bibliography: true
    # csl: chicago-fullnote-bibliography.csl
    callout-appearance: simple
    callout-icon: false
    reference-location: margin
    citation-location: margin
    cap-location: margin
    highlight-style: tango